version: "3"
services:
  app:
    container_name: quartz
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3838:8080
    volumes:
      - .:/app
      - ./content:/app/content:ro
